using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Relyf.Api.Models;
using Relyf.Service.Interfaces;
using System.Diagnostics;
using System.Security.Cryptography;
using System.Text;

namespace Relyf.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public sealed class IdeasController : ControllerBase
{
    private readonly IUpcycleIdeaService _service;
    private readonly RelyfDbContext _db;

    public IdeasController(IUpcycleIdeaService service, RelyfDbContext db)
    {
        _service = service;
        _db = db;
    }

    // ---- your existing GET stays exactly the same ----
    [HttpGet]
    public async Task<IActionResult> Get([FromQuery] string item, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(item))
            return BadRequest("Query param 'item' is required and must not be empty.");

        var trimmedItem = item.Trim();
        if (trimmedItem.Length < 2)
            return BadRequest("Query param 'item' must be at least 2 characters.");

        var messages = new List<(string Role, string Content)>
        {
            ("user", $"List creative, safe ways to reuse or upcycle: {trimmedItem}. Return as a numbered list.")
        };

        var ideas = await _service.GetIdeasFromMessagesAsync(messages, ct);
        if (string.IsNullOrWhiteSpace(ideas))
            return BadRequest("No ideas generated. Please provide a valid item.");

        return Ok(new { ideas });
    }

    // ---- NEW: persistence-friendly endpoint ----
    public sealed record GenerateIdeaRequest(
        int UserId,
        int? ItemId,
        string PromptText,          // required
        string? Model,
        decimal? Temperature,
        decimal? TopP,
        string? TitleHint
    );

    public sealed record GenerateIdeaResponse(
        int IdeaId,
        string Title,
        string IdeaText,
        int CoherePromptId,
        int? ItemId,
        int UserId
    );

    [HttpPost("generate")]
    public async Task<ActionResult<GenerateIdeaResponse>> Generate([FromBody] GenerateIdeaRequest req, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(req.PromptText))
            return BadRequest("PromptText is required.");

        // FK sanity
        if (!await _db.Users.AnyAsync(u => u.UserId == req.UserId, ct))
            return BadRequest("UserId does not exist.");
        if (req.ItemId.HasValue && !await _db.Items.AnyAsync(i => i.ItemId == req.ItemId.Value, ct))
            return BadRequest("ItemId does not exist.");

        // 1) Save CoherePrompt
        var prompt = new CoherePrompt
        {
            UserId = req.UserId,
            ItemId = req.ItemId,
            Model = req.Model,
            Temperature = req.Temperature,
            TopP = req.TopP,
            PromptText = req.PromptText
        };
        _db.CoherePrompts.Add(prompt);
        await _db.SaveChangesAsync(ct);

        // 2) Call your existing service using its multi-message pattern
        var sw = Stopwatch.StartNew();
        var messages = new List<(string Role, string Content)>
        {
            ("user", req.PromptText)
        };

        string ideaText;
        int status = 200;

        try
        {
            ideaText = await _service.GetIdeasFromMessagesAsync(messages, ct);
        }
        catch
        {
            status = 500;
            throw;
        }
        finally
        {
            sw.Stop();
            // 4) Log API call (minimal — you can extend with tokens if your service exposes them)
            byte[]? hash = null;
            using (var sha = SHA256.Create())
                hash = sha.ComputeHash(Encoding.UTF8.GetBytes(req.PromptText));

            _db.ApiRequestLogs.Add(new ApiRequestLog
            {
                UserId = req.UserId,
                Provider = "cohere",
                Endpoint = "/v2/chat",
                Model = req.Model ?? "command-r-plus",
                PromptHash = hash,
                TokensIn = null,
                TokensOut = null,
                StatusCode = status,
                DurationMs = (int)sw.ElapsedMilliseconds
            });
            await _db.SaveChangesAsync(ct);
        }

        if (string.IsNullOrWhiteSpace(ideaText))
            return BadRequest("No ideas generated by the AI.");

        // 3) Store AiIdea
        var title = string.IsNullOrWhiteSpace(req.TitleHint) ? "Upcycling Idea" : req.TitleHint.Trim();
        var idea = new AiIdea
        {
            CoherePromptId = prompt.CoherePromptId,
            ItemId = req.ItemId,
            UserId = req.UserId,
            Title = title,
            IdeaText = ideaText,
            Difficulty = null,
            EstTimeMin = null,
            EstCostUSD = null,
            TokensIn = null,
            TokensOut = null,
            ApiLatencyMs = (int)sw.ElapsedMilliseconds
        };
        _db.AiIdeas.Add(idea);
        await _db.SaveChangesAsync(ct);

        return CreatedAtAction(
            nameof(GetIdeaById),
            new { id = idea.IdeaId },
            new GenerateIdeaResponse(idea.IdeaId, idea.Title, idea.IdeaText, prompt.CoherePromptId, idea.ItemId, idea.UserId)
        );
    }

    // fetch the stored idea
    [HttpGet("{id:int}")]
    public async Task<ActionResult<AiIdea>> GetIdeaById(int id, CancellationToken ct)
    {
        var row = await _db.AiIdeas.AsNoTracking().FirstOrDefaultAsync(x => x.IdeaId == id, ct);
        return row is null ? NotFound() : row;
    }
}
