using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Relyf.Repository.Dapper;
using Relyf.Service.Interfaces;
using System.Diagnostics;
using System.Security.Claims;
using System.Security.Cryptography;
using System.Text;

namespace Relyf.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public sealed class IdeasController : ControllerBase
{
    private readonly IUpcycleIdeaService _service;
    private readonly ILookupRepository _lookup;
    private readonly ICoherePromptRepository _prompts;
    private readonly IApiRequestLogRepository _logs;
    private readonly IAiIdeaRepository _ideas;

    public IdeasController(IUpcycleIdeaService service,
                           ILookupRepository lookup,
                           ICoherePromptRepository prompts,
                           IApiRequestLogRepository logs,
                           IAiIdeaRepository ideas)
    {
        _service = service;
        _lookup = lookup;
        _prompts = prompts;
        _logs = logs;
        _ideas = ideas;
    }

    // ---------- helper ----------
    private int GetUserId()
    {
        var sub = User.FindFirstValue("sub") ?? User.FindFirstValue(ClaimTypes.NameIdentifier);
        if (!int.TryParse(sub, out var userId))
            throw new UnauthorizedAccessException("User id not found in token.");
        return userId;
    }

    // ---------- your existing “preview” endpoint stays open (no auth) ----------
    [HttpGet]
    [AllowAnonymous]
    public async Task<IActionResult> Get([FromQuery] string item, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(item))
            return BadRequest("Query param 'item' is required and must not be empty.");
        var trimmedItem = item.Trim();
        if (trimmedItem.Length < 2)
            return BadRequest("Query param 'item' must be at least 2 characters.");

        var messages = new List<(string Role, string Content)>
        { ("user", $"List creative, safe ways to reuse or upcycle: {trimmedItem}. Return as a numbered list.") };

        var ideas = await _service.GetIdeasFromMessagesAsync(messages, ct);
        if (string.IsNullOrWhiteSpace(ideas))
            return BadRequest("No ideas generated. Please provide a valid item.");

        return Ok(new { ideas });
    }

    // ---------- Dapper persistence endpoint (JWT required) ----------
    public sealed record GenerateIdeaRequest(
        int? ItemId,
        string PromptText,
        string? Model,
        decimal? Temperature,
        decimal? TopP,
        string? TitleHint
    );

    public sealed record GenerateIdeaResponse(
        int IdeaId,
        string Title,
        string IdeaText,
        int CoherePromptId,
        int? ItemId,
        int UserId
    );

    [HttpPost("generate")]
    [Authorize]
    public async Task<ActionResult<GenerateIdeaResponse>> Generate([FromBody] GenerateIdeaRequest req, CancellationToken ct)
    {
        if (string.IsNullOrWhiteSpace(req.PromptText))
            return BadRequest("PromptText is required.");

        var userId = GetUserId();

        // FK & ownership checks via Dapper
        if (!await _lookup.UserExistsAsync(userId, ct))
            return BadRequest("Authenticated user not found.");
        if (req.ItemId.HasValue && !await _lookup.ItemOwnedByUserAsync(req.ItemId.Value, userId, ct))
            return BadRequest("Item does not exist or is not owned by the current user.");

        // 1) save CoherePrompt
        var coherePromptId = await _prompts.CreateAsync(
            userId, req.ItemId, req.Model, req.Temperature, req.TopP, req.PromptText, ct);

        // 2) call Cohere via your service
        var sw = Stopwatch.StartNew();
        string ideaText;
        var status = 200;
        try
        {
            var messages = new List<(string Role, string Content)> { ("user", req.PromptText) };
            ideaText = await _service.GetIdeasFromMessagesAsync(messages, ct);
        }
        catch
        {
            status = 500;
            throw;
        }
        finally
        {
            sw.Stop();
            byte[] hash;
            using var sha = SHA256.Create();
            hash = sha.ComputeHash(Encoding.UTF8.GetBytes(req.PromptText));

            await _logs.CreateAsync(
                userId: userId,
                provider: "cohere",
                endpoint: "/v2/chat",
                model: req.Model ?? "command-r-plus",
                promptHash: hash,
                tokensIn: null,
                tokensOut: null,
                statusCode: status,
                durationMs: (int)sw.ElapsedMilliseconds,
                ct: ct
            );
        }

        if (string.IsNullOrWhiteSpace(ideaText))
            return BadRequest("No ideas generated by the AI.");

        // 3) store AiIdea
        var title = string.IsNullOrWhiteSpace(req.TitleHint) ? "Upcycling Idea" : req.TitleHint.Trim();
        var ideaId = await _ideas.CreateAsync(userId, req.ItemId ?? 0, title, ideaText, coherePromptId);

        return CreatedAtAction(
            nameof(GetIdeaById),
            new { id = ideaId },
            new GenerateIdeaResponse(ideaId, title, ideaText, coherePromptId, req.ItemId, userId)
        );
    }

    // fetch stored idea (JWT required & ownership enforced)
    [HttpGet("{id:int}")]
    [Authorize]
    public async Task<ActionResult<object>> GetIdeaById(int id, CancellationToken ct)
    {
        var userId = GetUserId();
        var row = await _ideas.GetByIdAsync(id, userId);
        return row is null ? NotFound() : Ok(row);
    }
}
